from enum import Enum


class TargetType(Enum):
    """
    货物枚举类型。通过截屏制作货物图片时，请确保截屏符合实际大小。
    """
    Chair = 'targets/Chair.jpg'
    Vegetable = 'targets/Vegetable.jpg'
    Bottle = 'targets/Bottle.jpg'
    Wood = 'targets/Wood.jpg'
    Food = 'targets/Food.jpg'
    Box = 'targets/Box.jpg'
    Sofa = 'targets/Sofa.jpg'
    Coal = 'targets/Coal.jpg'
    Screw = 'targets/Screw.jpg'
    Book = 'targets/Book.jpg'
    Cloth = 'targets/Cloth.jpg'
    Cotton = 'targets/Cotton.jpg'
    Quilt = 'targets/Quilt.jpg'
    Straw = 'targets/Straw.jpg'
    Mine = 'targets/Mine.jpg'
    Chicken = 'targets/Chicken.jpg'
    Kit = 'targets/Kit.jpg'
    Lamp = 'targets/Lamp.jpg'
    Mic = 'targets/Mic.jpg'
    Oil = 'targets/Oil.jpg'
    Silk = 'targets/Silk.jpg'
    Fertilizer = 'targets/Fertilizer.jpg'
    Cupboard = 'targets/Cupboard.jpg'
    Heels = 'targets/Heels.jpg'
    Steel = 'targets/Steel.jpg'
    Computer = 'targets/Computer.jpg'
    Gasoline = 'targets/Gasoline.jpg'
    Potting = 'targets/Potting.jpg'
    Chlorine = 'targets/Chlorine.jpg'
    Schoolbag = 'targets/Schoolbag.jpg'
    Rank_btn = 'targets/Rank_btn.jpg'
    Refrigerator = 'targets/Refrigerator.jpg'
    FlatCar = 'targets/FlatCar.jpg'
    BeachUmbrella = 'targets/BeachUmbrella.jpg'
    Helmet = 'targets/Helmet.jpg'